In [1]:
from AdditivePhylogeny import additivePhylogeny
from PhylogenyHelperFunctions import loadMatrixFile, printPhylogenyTree
import numpy as np

Example 1: Small Tree

In [2]:
D = np.array([[0, 13, 21, 22], [13, 0, 12, 13], [21, 12, 0, 13], [22, 13, 13, 0]])
print(D)

[[ 0 13 21 22]
 [13  0 12 13]
 [21 12  0 13]
 [22 13 13  0]]


In [3]:
t, w, n = additivePhylogeny(D, 4, 4)
printPhylogenyTree(t, w)

0->4:11
1->4:2
2->5:6
3->5:7
4->0:11
4->1:2
4->5:4
5->2:6
5->3:7
5->4:4


Example 2: Reading in from a text file

In [4]:
matrix, dim = loadMatrixFile("addPhyloTest.txt")
print(dim, matrix)

29 [[    0  3036  4777  1541  2766  6656  2401  4119  7488  4929  5344  3516
   1485  6392  2066  3216  7008  7206  1187  6491  3379  6262  6153  4927
   6670  4997  9010  5793  9032]
 [ 3036     0  6323  3087  4312  8202  1619  5665  9034  2205  6890   966
   3031  7938  3612   492  4284  8752  2023  8037  4925  3538  3429  6473
   3946  2273 10556  7339 10578]
 [ 4777  6323     0  4054  2571  3455  5688  1972  4287  8216  2143  6803
   4126  3191  3183  6503 10295  4005  4474  3290  2964  9549  9440  1726
   9957  8284  5809  2592  5831]
 [ 1541  3087  4054     0  2043  5933  2452  3396  6765  4980  4621  3567
    890  5669  1343  3267  7059  6483  1238  5768  2656  6313  6204  4204
   6721  5048  8287  5070  8309]
 [ 2766  4312  2571  2043     0  4450  3677  1913  5282  6205  3138  4792
   2115  4186  1172  4492  8284  5000  2463  4285  1173  7538  7429  2721
   7946  6273  6804  3587  6826]
 [ 6656  8202  3455  5933  4450     0  7567  3851  1082 10095  1872  8682
   6005  1992  506

In [5]:
t, w, n = additivePhylogeny(matrix, dim, dim)
printPhylogenyTree(t, w)

0->29:745
1->36:156
2->32:788
3->30:409
4->31:280
5->35:125
6->33:492
7->34:657
8->53:311
9->43:820
10->37:280
11->38:723
12->39:417
13->40:864
14->41:236
15->42:89
16->51:713
17->44:445
18->45:87
19->46:441
20->47:783
21->48:348
22->49:922
23->50:662
24->51:375
25->52:718
26->55:868
27->54:841
28->55:890
29->0:745
29->39:323
29->45:355
30->3:409
30->39:64
30->41:698
31->4:280
31->41:656
31->47:110
32->2:788
32->34:527
32->50:276
33->6:492
33->38:884
33->45:809
34->7:657
34->32:527
34->47:866
35->5:125
35->44:230
35->46:481
36->1:156
36->38:87
36->42:247
37->10:280
37->40:464
37->54:112
38->11:723
38->33:884
38->36:87
39->12:417
39->29:323
39->30:64
40->13:864
40->37:464
40->46:522
41->14:236
41->30:698
41->31:656
42->15:89
42->36:247
42->43:982
43->9:820
43->42:982
43->52:170
44->17:445
44->35:230
44->53:416
45->18:87
45->29:355
45->33:809
46->19:441
46->35:481
46->40:522
47->20:783
47->31:110
47->34:866
48->21:348
48->49:683
48->51:381
49->22:922
49->48:683
49->52:952
50->23:662
50->