In [1]:
from NeighborJoining import neighborJoining
from PhylogenyHelperFunctions import printPhylogenyTree
import numpy as np

In [2]:
D = np.array([[0, 23, 27, 20], [23, 0, 30, 28], [27, 30, 0, 30], [20,28,30, 0]])
print(D)

[[ 0 23 27 20]
 [23  0 30 28]
 [27 30  0 30]
 [20 28 30  0]]


In [3]:
t, w, v = neighborJoining(D, 4)
printPhylogenyTree(t, w)

0->4:8.0
1->5:13.5
2->5:16.5
3->4:12.0
4->0:8.0
4->3:12.0
4->5:2.0
5->1:13.5
5->2:16.5
5->4:2.0
